site_name: OPENBOOK
theme: material
nav:
  - Home: index.md
  - Introduction: 00_Introduction.md
  - Basics of Relativity: 01_Basics_of_Relativity.md
  - Quantum Mechanics Primer: 02_Quantum_Mechanics_Primer.md
  - Particle Physics and Atomic Structure: 03_Particle_Physics_and_Atomic_Structure.md
  - Thermodynamics Foundations: 04_Thermodynamics_Foundations.md
  - Chemical Bonding in Relativistic Contexts: 05_Chemical_Bonding_in_Relativistic_Contexts.md
  - Quantum Chemistry Basics: 06_Quantum_Chemistry_Basics.md
  - Particle Interactions in Chemical Reactions: 07_Particle_Interactions_in_Chemical_Reactions.md
  - Relativistic Effects in Heavy Elements: 08_Relativistic_Effects_in_Heavy_Elements.md
  - Advanced Thermodynamics for Chemistry: 09_Advanced_Thermodynamics_for_Chemistry.md
  - Summary and Future Perspectives: 10_Summary_and_Future_Perspectives.md
  - References:
    - Reference List: references/reference_list.md
    - External Links: references/external_links.md
  - Examples:
    - Advanced Topic Example: examples/sample_chapters/advanced_topic_example.md
  - Exercises:
    - Chapter 1: exercises/ch01_exercises.md
    - Chapter 2: exercises/ch02_exercises.md
    - Chapter 3: exercises/ch03_exercises.md
    - Chapter 4: exercises/ch04_exercises.md
    - Chapter 5: exercises/ch05_exercises.md
    - Chapter 6: exercises/ch06_exercises.md
